
### Create new User
POST /users HTTP/1.1
Host: {{local-server}}:9000
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "username": "johs1ndoe",
  "email": "john.does1@esxample.com",
  "avatar": "avatar-url",
  "gender": "MALE",
  "isAccountNonExpired": true,
  "isEnabled": true,
  "isCredentialsNonExpired": true,
  "isAccountNonLocked": true
}
