management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs
feign:
  circuitbreaker:
    enabled=true:
api:
  version: 1.0.0
  termsOfService: https://www.crcl.com/terms
  contactName: Chahir Chalouati
  contactEmail: chahir_chalouati@crcl.com
  licenseName: MIT
  licenseUrl: https://opensource.org/licenses/MIT
image-sizes:
  sizes:
    profile_picture:
      width: 170
      height: 170
      name: "profile_picture"
    cover_photo:
      width: 820
      height: 312
      name: "cover_photo"
    shared_image:
      width: 1200
      height: 630
      name: "shared_image"
    shared_link:
      width: 1200
      height: 628
      name: "shared_link"
    event_image:
      width: 1920
      height: 1080
      name: "event_image"
    group_cover_photo:
      width: 1640
      height: 856
      name: "group_cover_photo"
    gramify_story:
      width: 1080
      height: 1920
      name: "gramify_story"
    gramify_ad:
      width: 1200
      height: 628
      name: "gramify_ad"

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: localhost
    username: guest
    password: guest
web-socket:
  endPoint: /websocketApp
  prefixes: /app
  relayHost: localhost
  stompBrokerRelay: /topic
  relayPort: 61613
  clientLogin: guest
  clientPasscode: guest
client:
  iam:
    url: http://localhost:9999/iam
    name: iam
  sever-iam:
    url: http://localhost:9999/iam
    name: sever-iam
  audit:
    url: http://localhost:8000/audit
    name: audit
  srvAudit:
    url: http://localhost:8000/audit
    name: srvAudit
  comment:
    url: http://localhost:8001/comment
    name: comment
  srvComment:
    url: http://localhost:8001/comment
    name: srvComment
  friendship:
    url: http://localhost:8002/friendship
    name: friendship
  srvFriendship:
    url: http://localhost:8002/friendship
    name: srvFriendship
  date:
    url: http://localhost:8003/date
    name: date
  srvDate:
    url: http://localhost:8003/date
    name: srvDate
  marketplace:
    url: http://localhost:8004/marketplace
    name: marketplace
  srvMarketplace:
    url: http://localhost:8004/marketplace
    name: srvMarketplace
  notification:
    url: http://localhost:8005/notification
    name: notification
  srvNotification:
    url: http://localhost:8005/notification
    name: srvNotification
  post:
    url: http://localhost:8006/post
    name: post
  srvPost:
    url: http://localhost:8006/post
    name: srvPost
  profile:
    url: http://localhost:8007/profile
    name: profile
  srvProfile:
    url: http://localhost:8007/profile
    name: srvProfile
  reply:
    url: http://localhost:8008/reply
    name: reply
  srvReply:
    url: http://localhost:8008/reply
    name: srvReply
  storage:
    url: http://localhost:8009/storage
    name: storage
  srvStorage:
    url: http://localhost:8009/storage
    name: srvStorage
  story:
    url: http://localhost:8010/story
    name: story
  srvStory:
    url: http://localhost:8010/story
    name: srvStory
  tag:
    url: http://localhost:8011/tag
    name: tag
  srvTag:
    url: http://localhost:8011/tag
    name: srvTag

authorization:
  authorizationUrl: http://localhost:9999/authentication
  tokenUrl: http://localhost:9999/authentication/oauth2/token

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
web-socket:
  endPoint: /websocketApp
  prefixes: /app
  relayHost: rabbitmq
  stompBrokerRelay: /topic
  relayPort: 61613
  clientLogin: guest
  clientPasscode: guest
client:
  authentication:
    url: http://proxy-service:9999/authentication
    name: authentication
  srvAuthentication:
    url: http://proxy-service:9999/authentication
    name: srvAuthentication
  audit:
    url: http://audit:8000/audit
    name: audit
  srvAudit:
    url: http://audit:8000/audit
    name: srvAudit
  comment:
    url: http://comment:8001/comment
    name: comment
  srvComment:
    url: http://comment:8001/comment
    name: srvComment
  friendship:
    url: http://friendship:8002/friendship
    name: friendship
  srvFriendship:
    url: http://friendship:8002/friendship
    name: srvFriendship
  date:
    url: http://date:8003/date
    name: date
  srvDate:
    url: http://date:8003/date
    name: srvDate
  marketplace:
    url: http://marketplace:8004/marketplace
    name: marketplace
  srvMarketplace:
    url: http://marketplace:8004/marketplace
    name: srvMarketplace
  notification:
    url: http://notification:8005/notification
    name: notification
  srvNotification:
    url: http://notification:8005/notification
    name: srvNotification
  post:
    url: http://post:8006/post
    name: post
  srvPost:
    url: http://post:8006/post
    name: srvPost
  profile:
    url: http://profile:8007/profile
    name: profile
  srvProfile:
    url: http://profile:8007/profile
    name: srvProfile
  reply:
    url: http://reply:8008/reply
    name: reply
  srvReply:
    url: http://reply:8008/reply
    name: srvReply
  storage:
    url: http://storage:8009/storage
    name: storage
  srvStorage:
    url: http://storage:8009/storage
    name: srvStorage
  story:
    url: http://story:8010/story
    name: story
  srvStory:
    url: http://story:8010/story
    name: srvStory
  tag:
    url: http://tag:8011/tag
    name: tag
  srvTag:
    url: http://tag:8011/tag
    name: srvTag

authorization:
  authorizationUrl: http://proxy-service:9999/authentication
  tokenUrl: http://proxy-service:9999/authentication/oauth2/token

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
web-socket:
  endPoint: /websocketApp
  prefixes: /app
  relayHost: rabbitmq
  stompBrokerRelay: /topic
  relayPort: 61613
  clientLogin: guest
  clientPasscode: guest
client:
  authentication:
    url: http://proxy-service:9999/authentication
    name: authentication
  srvAuthentication:
    url: http://proxy-service:9999/authentication
    name: srvAuthentication
  audit:
    url: http://audit:8000/audit
    name: audit
  srvAudit:
    url: http://audit:8000/audit
    name: srvAudit
  comment:
    url: http://comment:8001/comment
    name: comment
  srvComment:
    url: http://comment:8001/comment
    name: srvComment
  friendship:
    url: http://friendship:8002/friendship
    name: friendship
  srvFriendship:
    url: http://friendship:8002/friendship
    name: srvFriendship
  date:
    url: http://date:8003/date
    name: date
  srvDate:
    url: http://date:8003/date
    name: srvDate
  marketplace:
    url: http://marketplace:8004/marketplace
    name: marketplace
  srvMarketplace:
    url: http://marketplace:8004/marketplace
    name: srvMarketplace
  notification:
    url: http://notification:8005/notification
    name: notification
  srvNotification:
    url: http://notification:8005/notification
    name: srvNotification
  post:
    url: http://post:8006/post
    name: post
  srvPost:
    url: http://post:8006/post
    name: srvPost
  profile:
    url: http://profile:8007/profile
    name: profile
  srvProfile:
    url: http://profile:8007/profile
    name: srvProfile
  reply:
    url: http://reply:8008/reply
    name: reply
  srvReply:
    url: http://reply:8008/reply
    name: srvReply
  storage:
    url: http://storage:8009/storage
    name: storage
  srvStorage:
    url: http://storage:8009/storage
    name: srvStorage
  story:
    url: http://story:8010/story
    name: story
  srvStory:
    url: http://story:8010/story
    name: srvStory
  tag:
    url: http://tag:8011/tag
    name: tag
  srvTag:
    url: http://tag:8011/tag
    name: srvTag

authorization:
  authorizationUrl: http://proxy-service:9999/authentication
  tokenUrl: http://proxy-service:9999/authentication/oauth2/token
