server:
  port: 8001
# openApi documentation
api:
  title: Comment Service
  description: API for Comment Service services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_comment
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          comment-service-oidc:
            provider: crcl-com
            client-id: comment-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          comment-service:
            provider: crcl-com
            client-id: comment-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://auth-server:9000
            jwk-set-uri: http://auth-server:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_comment
      host: mongo
      port: 27017
      authentication-database: admin
  security: &common-security
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          comment-service-oidc:
            provider: crcl-com
            client-id: comment-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          comment-service:
            provider: crcl.com
            client-id: comment-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://authentication-service:9000
            jwk-set-uri: http://authentication-service:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_comment
      host: mongo
      port: 27017
      authentication-database: admin
  security: *common-security
