server:
  port: 9999
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowed-origin-patterns:
              - "*"
      routes:
        - id: audit
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/audit/**
        - id: server-audit
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/audit/**"
        - id: comment
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/comment/**
        - id: server-comment
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/comment/**"
        - id: friendship
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/friendship/**
        - id: server-friendship
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/friendship/**"
        - id: date
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/date/**
        - id: server-date
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/date/**"
        - id: marketplace
          uri: http://127.0.0.1:8004
          predicates:
            - Path=/marketplace/**
        - id: server-marketplace
          uri: http://127.0.0.1:8004
          predicates:
            - Path=/marketplace/**"
        - id: notification
          uri: http://127.0.0.1:8005
          predicates:
            - Path=/notification/**
        - id: server-notification
          uri: http://127.0.0.1:8005
          predicates:
            - Path=/notification/**"
        - id: post
          uri: http://127.0.0.1:8006
          predicates:
            - Path=/post/**
        - id: server-post
          uri: http://127.0.0.1:8006
          predicates:
            - Path=/post/**"
        - id: profile
          uri: http://127.0.0.1:8007
          predicates:
            - Path=/profile/**
        - id: server-profile
          uri: http://127.0.0.1:8007
          predicates:
            - Path=/profile/**"
        - id: reply
          uri: http://127.0.0.1:8008
          predicates:
            - Path=/reply/**
        - id: server-reply
          uri: http://127.0.0.1:8008
          predicates:
            - Path=/reply/**"
        - id: storage
          uri: http://127.0.0.1:8009
          predicates:
            - Path=/storage/**
        - id: server-storage
          uri: http://127.0.0.1:8009
          predicates:
            - Path=/storage/**"
        - id: story
          uri: http://127.0.0.1:8010
          predicates:
            - Path=/story/**
        - id: server-story
          uri: http://127.0.0.1:8010
          predicates:
            - Path=/story/**"
        - id: tag
          uri: http://127.0.0.1:8011
          predicates:
            - Path=/tag/**
        - id: server-tag
          uri: http://127.0.0.1:8011
          predicates:
            - Path=/tag/**"



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          proxy-service-oidc:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-service:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowed-origin-patterns:
              - "*"
      routes: &routes
        - id: audit
          uri: http://audit:8000
          predicates:
            - Path=/audit/**
        - id: server-audit
          uri: http://audit:8000
          predicates:
            - Path=/audit/**"
        - id: comment
          uri: http://comment:8001
          predicates:
            - Path=/comment/**
        - id: server-comment
          uri: http://comment:8001
          predicates:
            - Path=/comment/**"
        - id: friendship
          uri: http://friendship:8002
          predicates:
            - Path=/friendship/**
        - id: server-friendship
          uri: http://friendship:8002
          predicates:
            - Path=/friendship/**"
        - id: date
          uri: http://date:8003
          predicates:
            - Path=/date/**
        - id: server-date
          uri: http://date:8003
          predicates:
            - Path=/date/**"
        - id: marketplace
          uri: http://marketplace:8004
          predicates:
            - Path=/marketplace/**
        - id: server-marketplace
          uri: http://marketplace:8004
          predicates:
            - Path=/marketplace/**"
        - id: notification
          uri: http://notification:8005
          predicates:
            - Path=/notification/**
        - id: server-notification
          uri: http://notification:8005
          predicates:
            - Path=/notification/**"
        - id: post
          uri: http://post:8006
          predicates:
            - Path=/post/**
        - id: server-post
          uri: http://post:8006
          predicates:
            - Path=/post/**"
        - id: profile
          uri: http://profile:8007
          predicates:
            - Path=/profile/**
        - id: server-profile
          uri: http://profile:8007
          predicates:
            - Path=/profile/**"
        - id: reply
          uri: http://reply:8008
          predicates:
            - Path=/reply/**
        - id: server-reply
          uri: http://reply:8008
          predicates:
            - Path=/reply/**"
        - id: storage
          uri: http://storage:8009
          predicates:
            - Path=/storage/**
        - id: server-storage
          uri: http://storage:8009
          predicates:
            - Path=/storage/**"
        - id: story
          uri: http://story:8010
          predicates:
            - Path=/story/**
        - id: server-story
          uri: http://story:8010
          predicates:
            - Path=/story/**"
        - id: tag
          uri: http://tag:8011
          predicates:
            - Path=/tag/**
        - id: server-tag
          uri: http://tag:8011
          predicates:
            - Path=/tag/**"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          proxy-service-oidc:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-service:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowed-origin-patterns:
              - "*"
      routes: *routes

  security:
    oauth2:
      client:
        registration:
          proxy-service-oidc:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-service:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
