server:
  port: 9000
# openApi documentation
api:
  title: iam Service
  description: API for iam services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_authentication
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.iam.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  loginPage: /authentication/login
  certificationBucket: cert
  failureForwardUrl: /authentication/login?error=true
  registrations:
    audit:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: audit
      uris:
        - http://localhost:8000
      scopes:
        - openid
        - read.audit
        - write.audit
      grantTypes:
        - client_credentials
    comment:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: comment
      uris:
        - http://localhost:8001
      scopes:
        - openid
        - read.comment
        - write.comment
      grantTypes:
        - client_credentials
    friendship:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: friendship
      uris:
        - http://localhost:8002
      scopes:
        - openid
        - read.friendship
        - write.friendship
      grantTypes:
        - client_credentials
    date:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: date
      uris:
        - http://localhost:8003
      scopes:
        - openid
        - read.date
        - write.date
      grantTypes:
        - client_credentials
    marketplace:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: marketplace
      uris:
        - http://localhost:8004
      scopes:
        - openid
        - read.marketplace
        - write.marketplace
      grantTypes:
        - client_credentials
    notification:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: notification
      uris:
        - http://localhost:8005
      scopes:
        - openid
        - read.notification
        - write.notification
      grantTypes:
        - client_credentials
    post:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: post
      uris:
        - http://localhost:8006
      scopes:
        - openid
        - read.post
        - write.post
      grantTypes:
        - client_credentials
    profile:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: profile
      uris:
        - http://localhost:8007
      scopes:
        - openid
        - read.profile
        - write.profile
      grantTypes:
        - client_credentials
    reply:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: reply
      uris:
        - http://localhost:8008
      scopes:
        - openid
        - read.reply
        - write.reply
      grantTypes:
        - client_credentials
    storage:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: storage
      uris:
        - http://localhost:8009
      scopes:
        - openid
        - read.storage
        - write.storage
      grantTypes:
        - client_credentials
    story:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: story
      uris:
        - http://localhost:8010
      scopes:
        - openid
        - read.story
        - write.story
      grantTypes:
        - client_credentials
    tag:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: tag
      uris:
        - http://localhost:8011
      scopes:
        - openid
        - read.tag
        - write.tag
      grantTypes:
        - client_credentials

minio:
  access-key: myaccesskey
  secret-key: mysecretkey
  url: http://localhost:47017
  buckets:
    - name: key-public-cert
      objectLock: false
      isDefault: true
    - name: key-private-cert
      objectLock: false
      isDefault: false
dummy:
  username: username
  password: password
  count: 100
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: dev_authentication
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.iam.migration
security:
  clientIp: social-service
  issuer: http://authentication-service:9000
  loginPage: /authentication/login
  certificationBucket: cert
  failureForwardUrl: /authentication/login?error=true
  registrations:
    audit:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: audit
      uris:
        - http://audit:8000
      scopes:
        - openid
        - read.audit
        - write.audit
      grantTypes:
        - client_credentials
    comment:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: comment
      uris:
        - http://comment:8001
      scopes:
        - openid
        - read.comment
        - write.comment
      grantTypes:
        - client_credentials
    friendship:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: friendship
      uris:
        - http://friendship:8002
      scopes:
        - openid
        - read.friendship
        - write.friendship
      grantTypes:
        - client_credentials
    date:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: date
      uris:
        - http://date:8003
      scopes:
        - openid
        - read.date
        - write.date
      grantTypes:
        - client_credentials
    marketplace:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: marketplace
      uris:
        - http://marketplace:8004
      scopes:
        - openid
        - read.marketplace
        - write.marketplace
      grantTypes:
        - client_credentials
    notification:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: notification
      uris:
        - http://notification:8005
      scopes:
        - openid
        - read.notification
        - write.notification
      grantTypes:
        - client_credentials
    post:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: post
      uris:
        - http://post:8006
      scopes:
        - openid
        - read.post
        - write.post
      grantTypes:
        - client_credentials
    profile:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: profile
      uris:
        - http://profile:8007
      scopes:
        - openid
        - read.profile
        - write.profile
      grantTypes:
        - client_credentials
    reply:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: reply
      uris:
        - http://reply:8008
      scopes:
        - openid
        - read.reply
        - write.reply
      grantTypes:
        - client_credentials
    storage:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: storage
      uris:
        - http://storage:8009
      scopes:
        - openid
        - read.storage
        - write.storage
      grantTypes:
        - client_credentials
    story:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: story
      uris:
        - http://story:8010
      scopes:
        - openid
        - read.story
        - write.story
      grantTypes:
        - client_credentials
    tag:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: tag
      uris:
        - http://tag:8011
      scopes:
        - openid
        - read.tag
        - write.tag
      grantTypes:
        - client_credentials
minio:
  access-key: myaccesskey
  secret-key: mysecretkey
  url: http://minio:9000
  buckets:
    - name: key-public-cert
      objectLock: false
      isDefault: true
    - name: key-private-cert
      objectLock: false
      isDefault: false
dummy:
  username: username
  password: password
  count: 100
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: dev_authentication
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.iam.migration
security:
  clientIp: 127.0.0.1
  issuer: http://authentication-service:9000
  loginPage: /authentication/login
  certificationBucket: cert
  failureForwardUrl: /authentication/login?error=true
  registrations:
    audit:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: audit
      uris:
        - http://audit:8000
      scopes:
        - openid
        - read.audit
        - write.audit
      grantTypes:
        - client_credentials
    comment:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: comment
      uris:
        - http://comment:8001
      scopes:
        - openid
        - read.comment
        - write.comment
      grantTypes:
        - client_credentials
    friendship:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: friendship
      uris:
        - http://friendship:8002
      scopes:
        - openid
        - read.friendship
        - write.friendship
      grantTypes:
        - client_credentials
    date:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: date
      uris:
        - http://date:8003
      scopes:
        - openid
        - read.date
        - write.date
      grantTypes:
        - client_credentials
    marketplace:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: marketplace
      uris:
        - http://marketplace:8004
      scopes:
        - openid
        - read.marketplace
        - write.marketplace
      grantTypes:
        - client_credentials
    notification:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: notification
      uris:
        - http://notification:8005
      scopes:
        - openid
        - read.notification
        - write.notification
      grantTypes:
        - client_credentials
    post:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: post
      uris:
        - http://post:8006
      scopes:
        - openid
        - read.post
        - write.post
      grantTypes:
        - client_credentials
    profile:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: profile
      uris:
        - http://profile:8007
      scopes:
        - openid
        - read.profile
        - write.profile
      grantTypes:
        - client_credentials
    reply:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: reply
      uris:
        - http://reply:8008
      scopes:
        - openid
        - read.reply
        - write.reply
      grantTypes:
        - client_credentials
    storage:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: storage
      uris:
        - http://storage:8009
      scopes:
        - openid
        - read.storage
        - write.storage
      grantTypes:
        - client_credentials
    story:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: story
      uris:
        - http://story:8010
      scopes:
        - openid
        - read.story
        - write.story
      grantTypes:
        - client_credentials
    tag:
      refresh-token-access-time-to-leave: 8000
      secret: secret
      token-access-time-to-leave: 8000
      id: tag
      uris:
        - http://tag:8011
      scopes:
        - openid
        - read.tag
        - write.tag
      grantTypes:
        - client_credentials
minio:
  access-key: myaccesskey
  url: http://minio:9000
  secret-key: mysecretkey
  buckets:
    - name: key-public-cert
      objectLock: false
      isDefault: true
    - name: key-private-cert
      objectLock: false
      isDefault: false
dummy:
  username: username
  password: password
  count: 100
