server:
  port: 8006
# openApi documentation
api:
  title: infrastructure Service
  description: API for infrastructure services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_infrastructure
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          infrastructure-service-oidc:
            provider: crcl.com
            client-id: infrastructure-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          infrastructure-service:
            provider: crcl.com
            client-id: infrastructure-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_infrastructure
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          infrastructure-service-oidc:
            provider: crcl.com
            client-id: infrastructure-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          infrastructure-service:
            provider: crcl.com
            client-id: infrastructure-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_infrastructure
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          infrastructure-service-oidc:
            provider: crcl.com
            client-id: infrastructure-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          infrastructure-service:
            provider: crcl.com
            client-id: infrastructure-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
