server:
  port: 8004
# openApi documentation
api:
  title: Marketplace Service
  description: API for Marketplace Service services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_marketplace
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          marketplace-service-oidc:
            provider: crcl-com
            client-id: marketplace-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          marketplace-service:
            provider: crcl-com
            client-id: marketplace-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://auth-server:9000
            jwk-set-uri: http://auth-server:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_marketplace
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          marketplace-service-oidc:
            provider: crcl-com
            client-id: marketplace-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          marketplace-service:
            provider: crcl.com
            client-id: marketplace-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://authentication-service:9000
            jwk-set-uri: http://authentication-service:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_marketplace
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          marketplace-service-oidc:
            provider: crcl-com
            client-id: marketplace-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          marketplace-service:
            provider: crcl.com
            client-id: marketplace-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://authentication-service:9000
            jwk-set-uri: http://authentication-service:9000/oauth2/jwks
