server:
  port: 80010
# openApi documentation
api:
  title: profile Service
  description: API for profile services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_profile
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          profile-service-oidc:
            provider: crcl.com
            client-id: profile-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          profile-service:
            provider: crcl.com
            client-id: profile-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_profile
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          profile-service-oidc:
            provider: crcl.com
            client-id: profile-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          profile-service:
            provider: crcl.com
            client-id: profile-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_profile
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          profile-service-oidc:
            provider: crcl.com
            client-id: profile-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          profile-service:
            provider: crcl.com
            client-id: profile-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
