server:
  port: 8010
# openApi documentation
api:
  title: Story Service
  description: API for Story Service services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_story
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          story-service-oidc:
            provider: crcl-com
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          story-service:
            provider: crcl-com
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://auth-server:9000
            jwk-set-uri: http://auth-server:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_story
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          story-service-oidc:
            provider: crcl-com
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          story-service:
            provider: crcl.com
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://authentication-service:9000
            jwk-set-uri: http://authentication-service:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_story
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          story-service-oidc:
            provider: crcl-com
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          story-service:
            provider: crcl.com
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          crcl-com:
            issuer-uri: http://authentication-service:9000
            jwk-set-uri: http://authentication-service:9000/oauth2/jwks
